# Generated by Django 2.2.9 on 2022-02-15 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
